name: Build and Deploy RuoYi Admin

on:
  push:
    branches:
      - main 
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Install all modules
      run: |
        mvn clean install -DskipTests -U
    
    - name: Build project
      run: |
        mvn clean package -DskipTests
        cd ruoyi-admin
        ls -lh target
    
    - name: Deploy jar to server
      uses: appleboy/scp-action@master
      with:
        strip_components: 2
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        source: ruoyi-admin/target/ruoyi-admin.jar
        target: /root/ruoyi-admin/

    - name: Run jar on server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          cd /root/ruoyi-admin/
          chmod +x start.sh
          sh start.sh
