name: Build and Deploy RuoYi Admin

on:
  workflow_dispatch:  # ✅ 手动点击运行

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Build with Maven
      run: |
       cd ruoyi-admin
       mvn clean package -DskipTests
       
    - name: Deploy jar to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        source: ruoyi-admin/target/ruoyi-admin.jar
        target: /root/ruoyi-admin/

    - name: Run jar on server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          sh /root/ruoyi-admin/start.sh
